# Generated by Django 5.0.2 on 2024-03-08 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='car_details',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='reservation',
            name='car_number',
            field=models.CharField(default='', max_length=255),
        ),
    ]
