# Generated by Django 5.0.2 on 2024-03-08 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_reservation_car_details_reservation_car_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='payment_id',
            field=models.CharField(default='', max_length=255),
        ),
    ]
