# Generated by Django 5.0.2 on 2024-03-16 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_parkingslot_price_reservation_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='price',
        ),
    ]
