# Generated by Django 5.0.2 on 2024-03-16 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_reservation_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='phone_number',
            field=models.CharField(default='0000000000', max_length=250),
        ),
    ]
