# Generated by Django 5.0.2 on 2024-03-20 07:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_reservation_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parking_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.parkingplace')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'parking_place')},
            },
        ),
    ]
