# Generated by Django 5.0.2 on 2024-03-20 08:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_supportplace'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='support',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'support'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supported_reservations', to=settings.AUTH_USER_MODEL),
        ),
    ]
