# Generated by Django 5.0.2 on 2024-03-20 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_reservation_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='payment_mode',
            field=models.CharField(default='COD', max_length=255),
        ),
    ]
